### ISSUE TITLE
No users table in sample.sql

### ISSUE THREAD

**Issue by the-reboot-button** [optikalefx/OpenJS-Grid#101]
Hi,

I am using the latest version (2.1).

I have found the discussion on issue #80 (https://github.com/optikalefx/OpenJS-Grid/issues/80).  I am having the same issue. 

In the sample.sql file there are no **users** table.  My username and password is correct (I have verified it).

Sorry - I am semi-new to this and I am trying to find my feet.

**Comment by the-reboot-button** [comment]
Any feedback at all?

**Comment by optikalefx** [comment]
Hey, Don't mean to hold you up here. That issue is likely a credentials or naming issue of the table or database. I'm lacking time at the moment to help more extensively, but triple check all of your credentials, names of tables, fields in both your code and in your database to make sure you're using the right names.

**Comment by the-reboot-button** [comment]
Hi,

OK ... I'm gonna run it from scratch.  

Step 1: Import data into mysql db
Step 2: Upload files
Step 3: Update mysql connect user info in ajax.php

Let's try

**Comment by the-reboot-button** [comment]
It seems to be the version of either php I was running on or the version of MySQL.  I have migratet to an earlier version of php and it seems to be fine now ;-)

**Comment by optikalefx** [comment]
Boy o Boy does this need an update. Thanks for looking into that issue.
