### ISSUE TITLE
Other DBs?

### ISSUE THREAD

**Issue by ioconnor** [optikalefx/OpenJS-Grid#6]
I'm wondering if you are planning on adding support for sqlite and postgres?
(Is this the right place to ask questions?)

**Comment by cscopp** [comment]
Hi Sean, I've been looking for a grid solution to implement and yours looks great! I just DLed v 2.1.7 and noticed in the ajax.php file you are still using mysql_connect rather than PDO (or at least mysqli). From what I understand, mysql_connect is being totally REMOVED in PHP 7 so anyone that upgrades their PHP is going to break this. Have you given any further thought to PDOizing it?

Best Regards,
Chris Scopp

**Comment by optikalefx** [comment]
I haven't had time to bring this up to date, but please feel free to make a fork that is PDO ready, it should be very easy

**Comment by cscopp** [comment]
I currently have 3 projects going on so I'm not sure if I can do it now, but I've always wanted to contribute to an open source project so I'll let you know if my schedule clears up.

It may not be quite as easy as it may seem. We would not only need to replace the actual connection itself, but other things as well. For example, mysql_real_escape_string in your grid.php is also deprecated (and I believe removed in PHP 7) so we probably want http://php.net/manual/en/function.filter-input.php instead. Also, anytime you have other calls such as mysql_query and mysql_fetch_assoc also need to be changed. It might be a little bit of an undertaking to make sure nothing else gets broken in the process, I'm sure you know how that goes!

Take Care brother!
Chris

**Comment by optikalefx** [comment]
Yep it's a few things, but it really does need to get done. I can help with questions if you get stuck anywhere. I'm still have my 8 years of PHP experience even if I use node now a days. Ha
