### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by MGA555** [optikalefx/OpenJS-Grid#67]
In looking at your various videos, I thought you had a demo download, and a getting started tutorial.  I can't find either.  I tried getting started, but I get stuck with a "Loading" message.  I'm guessing it's looking for a database, which I could install using sample.sql, but where do I put the credentials is set for the database?  Apologies for the abuse of GitHub issues, but I am unaware of any other forum to ask such questions. 

Where are such getting setup issues best addressed,   thanks

**Comment by optikalefx** [comment]
Sorry if the getting started seems lacking.  Sometimes as the guy who makes the stuff it's hard to see it as your users.  At any rate, I don't have a video that is exactly what you're looking for, but your local mysql credentials go in the file that's connecting to your database.  Which in my demo is `ajax.php` Right here https://github.com/optikalefx/OpenJS-Grid/blob/master/ajax.php#L3-L4

Make sure the creds match your local, so make sure you know if you're using a password or not, if you're root or not etc etc.  Also make sure you actually import the given db file.  Lastly note that this is trying to connect to the database called "test" so whatever you named yours, change that, or if you name it "test" then you can let it be.

Let me know if you have other questions, and this forum is the best place for these questions.

**Comment by MGA555** [comment]
That did it!  Thanks so much.

BTW, you videos are great, and since it did take me some struggling and confusion to get the demo running, I would highly recommend a video on how to get started.  Since you have done such a good job on making OpenJS Grid simple to use, the video would be pretty short, but immensely helpful.

thanks again

**Comment by MGA555** [comment]
As additional encouragement to make an "Getting Started" video, or post, consider that it was an educated guess on my part that index.php actually displayed the demo database, and that I needed to install the files in a server (WAMP in my case) environment.  Many newbies will struggle with those things in the beginning.  Why not start them off on the right foot.

thanks again for your help, AND a great resource.  Any idea when you might tackle "exports"?

**Comment by optikalefx** [comment]
Yea I should mention that in order to use PHP you need a web server. You don't have to hit index.php actually. If you just hit http://localhost/ it will just use index.php.

I generally don't make videos for newbies. There are 10 million of those out there. The goal of my channel and my tools is for people like myself.  But it's always good to have some info for those getting started.

I've abandoned PHP for NodeJS. So the next version of OpenJS Grid will most likely be fully client side and not have a server component to it. Or it will have a very simple server example for PHP, Node and Other.  I don't have a date slated for this yet though.
